### ISSUE TITLE
Type definition file error

### ISSUE THREAD

**Issue by glitchassassin** [screepers/screeps-arena-typescript-starter#21]
I'm not sure this is actually a breaking error, but it shows up in every build:

```
rollup v2.70.1
bundles src/arena_tutorial_9/main.ts → dist/arena_tutorial_9...
rpt2: options error TS2688: Cannot find type definition file for 'screeps-arena'.
created dist/arena_tutorial_9 in 2.5s
```

I think it's because `./node_modules/@types` is set as a type root, but there's no d.ts file under `./node_modules/@types/screeps-arena`.

**Comment by thmsndk** [comment]
The error does not cause in issues as it is now, and I think you might be right, The reason probably is because we are referencing the /dist folder in the typed-screeps-arena repo.

I am unsure how to solve it currently, and it's a minor annoyance. we can either update the readme to reference this issue or try and figure out how to solve it.

**Comment by glitchassassin** [comment]
Found an easy solution! Just install the develop package without putting it under @types.

**Comment by thmsndk** [comment]
Should have been solved by this on the types repository https://github.com/screepers/typed-screeps-arena/pull/13
